### ISSUE TITLE
Skip link shouldn't be part of site navigation

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/digitized_av_qc#10]
## Describe the bug
The skip link is inside of a `<nav>` element, which isn't the best practice for these.

## Expected behavior
The skip link can just sit inside the `<body>` element before the header.

## Impact on your work
The purpose of the skip link is to skip navigation or other repetitive part of the page (which isn't a big factor on this site, but still best practice to have one that skips the header), so if it's placed inside a `<nav>` it can cause confusion when someone is using assistive tech.

**Comment by helrond** [comment]
fixed in bbb89ce53a80ceee45d689f8d9b7507392c733a1
